######### NORMAL OPERATION  ###########

### Read all question
GET http://localhost:3000/index

### Read all questions with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/index/questions

### 
GET {{baseUrl}}/questions?quiz=1

