@baseUrl = http://localhost:3000

### Read all users
GET {{baseUrl}}/users

### login one user
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "username" : "test@student.vinci.be",
    "password": "test"
}

### register
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "username" : "kev@student.vinci.be",
    "password": "test",
    "confirmationPassword":"test"
    
}
