@baseUrl = http://localhost:3000

### Read all users
GET {{baseUrl}}/users

### login one user
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "username" : "kevin.bationo@student.vinci.be",
    "password": "test"
}

### login one user
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "username" : "etudiant@student.vinci.be",
    "password": "mdp",
    "confirmationPassword":"mdp"
    
}
